name       : python-futures
version    : 3.2.0
release    : 2
source     :
    - https://github.com/agronholm/pythonfutures/archive/3.2.0.tar.gz : fc959e162a3ea775c827f8a5e1810ecd175dbb986c2b16864b47fe491ad6950b
license    : Python-2.0
component  : programming.python
summary    : Backport of the concurrent.futures package from Python 3.2
description: |
    Backport of the concurrent.futures package from Python 3.2
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
